### PR TITLE
Fix race-condition during vips load

### LINKED ISSUE #107: undefined method 'new_from_file' for Vips::Image:Class
I am getting errors such as `undefined method 'new_from_file' for Vips::Image:Class` or `uninitialized constant Vips::Image` from here, seemingly randomly:

https://github.com/tomasc/dragonfly_libvips/blob/master/lib/dragonfly_libvips/processors/thumb.rb#L24

`vips` is required, I have vips-8.5.2 installed (Ubuntu 14), with `gobject-introspection (3.1.1)`, `ruby-vips (1.0.4)`

Can't seem to track down the source of the issue … any ideas please?

Thanks,
Tomas

### PR DESCRIPTION
**Pull request by felixbuenemann**
This avoids the problematic lazy-loading of the GI module which goes
horribly wrong if it is attempted by two threads at once.

If one really wants to delay laoding of the gi module, it is possible to
set $vips_skip_autoload = true before requiring vips or simply don't
require vips until it is needed.

The race condition can be reproduced with the following code:

```ruby
require "vips"
10.times do
  fork do
    q=Queue.new
    th=[]
    th << Thread.new { q << (Vips::Access::SEQUENTIAL rescue $!) }
    th << Thread.new { q << (Vips::Image.new_from_array([0]) rescue $!) }
    th.map(&:join)
    puts q.pop.inspect
    puts q.pop.inspect
  end
end
Process.waitall
```

Without this fix, the code will print random exceptions like:

```
#<ArgumentError: Vips.init: wrong number of arguments (0 for 1)>
#<NoMethodError: undefined method `new_from_array' for Vips::Image:Class
#<NameError: uninitialized constant Vips::Image
```

This fixes #107.

### CODE REVIEW

**Comment by jcupitt** [comment]
That looks much better. Could it need a `Thread.exclusive` as well?

**Comment by felixbuenemann** [comment]
Sorry too many bottles of wine, could you elaborate?

I tried using a mutex, but it didn't yreally help, because we basically would have to avoid entering const/method missing as soon as another init is running or we're screwed.

**Comment by felixbuenemann** [comment]
So to be more specific: I tried putting a mutex aroud init with a boolean to abort early so it only ran once, but that still didn’t fix the issue so I chose to get rid of the lazy loading which has the benefit of being cow friendly because we allocate memory before the fork.

I also changed the method name because it was clashing with a method defined by GI and I found it very confusing to have the same method with different signatures and behavior depending on the object lifecycle. (That’s why you see the wrong number of arguments exception above.)

**Comment by jcupitt** [comment]
Hi again, you're right, I'd had too many bottles of wine too. This is great, let's merge!

I'll update the gem later today.

**Comment by jcupitt** [comment]
OK, 1.0.6 is up and has this fix, plus a much faster `#to_a`. Thanks again!

**Pull request merged**
